#!/bin/bash
clear
echo -e "\033[38;5;82mINSTALANDO PAINEL DE ATUALIZAÇÕES PARA O CONECTA 4G  \033[0m"
sleep 4s
apt install wget -y; bash <(wget -qO- https://github.com/Lockednet/LOCKEDWEB/raw/main/install/sincpainel.sh)